import 'package:module_commons/models/entity/process.dart';
import 'package:module_commons/models/enum/process_status.dart';

class IProcessClient {
  Future<List<Process>> getProcesses(String startDate, String endDate) =>
      Future.delayed(Duration(seconds: 1)).then((value) => [
            Process(
                number: 99944827,
                status: ProcessStatus.validatingForm,
                principalTenantName: 'Jose da Silva',
                insuranceCompany: 'Pottencial',
                startDate: '01/01/2022',
                expirationDate: '01/01/2023',
                street: 'Rua Iguape',
                complement: 'BL 10, APTO 12',
                city: 'Ribeirao Preto',
                district: 'Jardim Paulista',
                uf: 'SP',
                tenants: ['Joaozin', 'Maria']),
            Process(
                number: 99944827,
                status: ProcessStatus.approved,
                principalTenantName: 'Carlos Silva',
                insuranceCompany: 'Porto Seguro',
                startDate: '01/01/2022',
                expirationDate: '01/01/2023',
                street: 'Rua Iguape',
                complement: 'BL 10, APTO 12',
                city: 'Ribeirao Preto',
                district: 'Jardim Paulista',
                uf: 'AC',
                tenants: ['Jozete', 'Claudin', 'CLeyto rasta']),
            Process(
                number: 99944827,
                status: ProcessStatus.emittingProposal,
                principalTenantName: 'Alberto Silva',
                insuranceCompany: 'Porto Seguro',
                startDate: '01/01/2022',
                expirationDate: '01/01/2023',
                street: 'Rua Iguape',
                complement: 'BL 10, APTO 12',
                city: 'Ribeirao Preto',
                district: 'Jardim Paulista',
                uf: 'MG',
                tenants: []),
            Process(
                number: 99944827,
                status: ProcessStatus.sendToInsuranceCompany,
                principalTenantName: 'Joaquin Silva',
                insuranceCompany: 'Pottencial',
                startDate: '01/01/2022',
                expirationDate: '01/01/2023',
                street: 'Rua Iguape',
                complement: 'BL 10, APTO 12',
                city: 'Ribeirao Preto',
                district: 'Jardim Paulista',
                uf: 'SP',
                tenants: []),
            Process(
                number: 99944827,
                status: ProcessStatus.concluded,
                principalTenantName: 'Jose da Silva',
                insuranceCompany: 'Porto Seguro',
                startDate: '01/01/2022',
                expirationDate: '01/01/2023',
                street: 'Rua Iguape',
                city: 'Sao Paulo',
                district: 'Jardim Paulista',
                uf: 'SP',
                tenants: ['Amadeu amaral', 'Chico pino']),
            Process(
                number: 99944827,
                status: ProcessStatus.refused,
                principalTenantName: 'Jose da Silva',
                insuranceCompany: 'Porto Seguro',
                startDate: '01/01/2022',
                expirationDate: '01/01/2023',
                street: 'Rua Iguape',
                city: 'Ribeirao Preto',
                district: 'Jardim Paulista',
                uf: 'SP',
                tenants: []),
            Process(
                number: 99944827,
                status: ProcessStatus.canceled,
                principalTenantName: 'Jose da Silva',
                insuranceCompany: 'Porto Seguro',
                startDate: '01/01/2022',
                expirationDate: '01/01/2023',
                street: 'Rua Iguape',
                city: 'Fortaleza',
                district: 'Jardim Paulista',
                uf: 'RJ',
                tenants: ['Tarantela']),
          ]);
}
