import 'package:module_commons/models/entity/process.dart';
import 'package:module_commons/models/enum/process_status.dart';

class IResumedProcessClient {
  Future<List<Process>> getProcesses() {
    return Future.delayed(const Duration(seconds: 1)).then((value) => [
          Process(
              number: 99944827,
              status: ProcessStatus.validatingForm,
              principalTenantName: 'Jose da Silva',
              insuranceCompany: 'Porto Seguro',
              startDate: '01/01/2022',
              expirationDate: '01/01/2023',
              street: 'Rua Iguape',
              complement: 'BL 10, APTO 12',
              city: 'Ribeirao Preto',
              district: 'Jardim Paulista',
              uf: 'SP',
              tenants: []),
          Process(
              number: 99944827,
              status: ProcessStatus.approved,
              principalTenantName: 'Jose da Silva',
              insuranceCompany: 'Porto Seguro',
              startDate: '01/01/2022',
              expirationDate: '01/01/2023',
              street: 'Rua Iguape',
              complement: 'BL 10, APTO 12',
              city: 'Ribeirao Preto',
              district: 'Jardim Paulista',
              uf: 'SP',
              tenants: []),
          Process(
              number: 99944827,
              status: ProcessStatus.emittingProposal,
              principalTenantName: 'Jose da Silva',
              insuranceCompany: 'Porto Seguro',
              startDate: '01/01/2022',
              expirationDate: '01/01/2023',
              street: 'Rua Iguape',
              complement: 'BL 10, APTO 12',
              city: 'Ribeirao Preto',
              district: 'Jardim Paulista',
              uf: 'SP',
              tenants: []),
          Process(
              number: 99944827,
              status: ProcessStatus.sendToInsuranceCompany,
              principalTenantName: 'Jose da Silva',
              insuranceCompany: 'Porto Seguro',
              startDate: '01/01/2022',
              expirationDate: '01/01/2023',
              street: 'Rua Iguape',
              complement: 'BL 10, APTO 12',
              city: 'Ribeirao Preto',
              district: 'Jardim Paulista',
              uf: 'SP',
              tenants: []),
          Process(
              number: 99944827,
              status: ProcessStatus.signedDocuments,
              principalTenantName: 'Jose da Silva',
              insuranceCompany: 'Porto Seguro',
              startDate: '01/01/2022',
              expirationDate: '01/01/2023',
              street: 'Rua Iguape',
              city: 'Ribeirao Preto',
              district: 'Jardim Paulista',
              uf: 'SP',
              tenants: []),
          Process(
              number: 99944827,
              status: ProcessStatus.emittingPolicy,
              principalTenantName: 'Jose da Silva',
              insuranceCompany: 'Porto Seguro',
              startDate: '01/01/2022',
              expirationDate: '01/01/2023',
              street: 'Rua Iguape',
              city: 'Ribeirao Preto',
              district: 'Jardim Paulista',
              uf: 'SP',
              tenants: []),
          Process(
              number: 99944827,
              status: ProcessStatus.emittingProposal,
              principalTenantName: 'Jose da Silva',
              insuranceCompany: 'Porto Seguro',
              startDate: '01/01/2022',
              expirationDate: '01/01/2023',
              street: 'Rua Iguape',
              city: 'Ribeirao Preto',
              district: 'Jardim Paulista',
              uf: 'SP',
              tenants: []),
        ]);
  }
}
