name: module_commons
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  brasil_fields: ^1.4.5
  date_time_picker: ^2.1.0
  easy_mask: ^2.0.1
  flutter_bloc: ^8.0.1
  flutter_modular: ^5.0.3
  flutter_svg: ^1.1.0
  flux_validator_dart: ^2.0.0
  freezed_annotation: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  logger: ^1.1.0
  build_runner:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.pmgdash.module_commons
    iosBundleIdentifier: com.pmgdash.moduleCommons
