name: module_real_state
description: A new Flutter module project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  module_commons:
    path: '../module_commons'
  
  module_design:
    path: '../module_design'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module_real_state
    iosBundleIdentifier: com.example.moduleRealState
